name: Deploy to AWS Production environment via Terraform

on:
  push:
     branches: [main]
     paths:
      - './terraform/environments/dev/**'
      - '.github/workflows/terraform-deploy-dev.yml'
  pull_request:
     branches: [main]

permissions:
  id-token: write     # Required for OIDC
  contents: read

jobs:
  terraform:
    name: Terraform Plan for ${{ matrix.env }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - env: prod
            branch: main

    # Filter job by branch using matrix + github.ref
    steps:
      - name: Skip job if branch doesn't match
        if: github.ref != format('refs/heads/{0}', matrix.branch)
        run: echo "Skipping job for unmatched branch."

      - name: Checkout code
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - name: Setup Terraform
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        run: terraform init

      - name: Terraform Format Check
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        run: terraform fmt -check

      - name: Terraform Validate
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        run: terraform validate

      - name: Terraform Plan
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        run: terraform plan -var-file="environments/${{ matrix.env }}/terraform.tfvars"

      - name: Run TFSec
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Run Checkov
        if: github.ref == format('refs/heads/{0}', matrix.branch)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="environments/${{ matrix.env }}/terraform.tfvars"